version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - cd client && npm install && cd ..
      - cd api && npm install && cd ..
  build:
    commands:
      - cd client && npm run build && cd ..
  post_build:
    commands:
      - mv ./client/build ./build
artifacts:
  secondary-artifacts:
    client:
      files:
        - '**/*'
      base-directory: build
    api:
      files:
        - '**/*'
      base-directory: api